### ISSUE TITLE
Merger/contributions?

### ISSUE THREAD

**Issue by mkearney** [ropensci/googleLanguageR#16]
So I just realized this package exists, which is unfortunate because [I recently started making the same package](https://github.com/mkearney/googleapis).

What are your plans with this? I'd like to keep working on the package, but I'd rather the work not be redundant. Are you open to contributions? Flexible with vision?

**Comment by MarkEdmondson1234** [comment]
Ah the perils of open source :) That has happened to me before when I tried to make a Stripe API package, only to find one on CRAN just before my submission. 

I am very much open to collaboration, and in fact have already had a lot of suggestions through an rOpenSci submission https://github.com/ropensci/onboarding/issues/127

I also have a few other packages to maintain, so would appreciate the help keeping on top of this one. 

Totally open to what you would like the package to do etc. you probably have a better idea on its applications than I do. I was going to use your package rtweet to make some kind of "fake news" detector but not much past planning for that. 

It does depend on googleAuthR that is the central work horse for all my Google API packages, but hopefully that is not a problem. Open to improving that too as it's due a refactor to v1.
