### ISSUE TITLE
Add classify text endpoint

### ISSUE THREAD

**Issue by MarkEdmondson1234** [ropensci/googleLanguageR#20]
https://cloud.google.com/natural-language/docs/beta

**Comment by markhwhiteii** [comment]
Is this still on the docket to be done? I'd like to be able to use the `classifyText` method: https://cloud.google.com/natural-language/docs/reference/rest/v1/documents/classifyText. The API documentation and the source code for `gl_nlp_single` makes it seem like all that would need to be done is allowing `classifyText` to be a possible `nlp_type` argument to `gl_nlp`. I've tried doing this myself to test, but I'm getting hung-up on `match.args` throwing me a bunch of errors.

**Comment by MarkEdmondson1234** [comment]
Yes its going to be done before the next release on CRAN.  It should be as you say just adding it to the options, if you throw some code up I'll see what the issue is and it will hurry up its implementation :)

**Comment by MarkEdmondson1234** [comment]
@markhwhiteii I have implemented it now, do please try it out

**Comment by MarkEdmondson1234** [comment]
Todo:

- [ ] add documentation

**Comment by MarkEdmondson1234** [comment]
Issues with the tests https://github.com/nealrichardson/httptest/issues/13
