### ISSUE TITLE
Error while using gl_speech()

### ISSUE THREAD

**Issue by Punitha89** [ropensci/googleLanguageR#27]
Hi,

I am trying to convert the wav file to text, i.e. audio to text. Where i am using googleLanguageR package to convert the data, for this i am using gl_speech(test_audio) method, its throwing an error saying **"2018-01-17 20:22:02> No authorization yet in this session!
2018-01-17 20:22:02> No .httr-oauth file exists in current working directory. Do library authentication steps to provide credentials.
Error: Invalid token**

Please can anyone help me in debugging this issue.

**Comment by MarkEdmondson1234** [comment]
Have you authenticated as per the website? http://code.markedmondson.me/googleLanguageR/#authentication

**Comment by Punitha89** [comment]
I need to change some proxy settings to perform those steps. Let me check and perform those steps and update you. Thanks a lot for the response.

**Comment by Punitha89** [comment]
Thank you so much, when i run woman1_wb.wav i.e."test_audio <- system.file("woman1_wb.wav", package = "googleLanguageR")" this code works but when I try running the my recordings, it throws error saying 

Request failed [400]. Retrying in 1 seconds...
Request failed [400]. Retrying in 1 seconds...
2018-01-23 23:03:33> Request Status Code: 400
Scopes: https://www.googleapis.com/auth/cloud-platform
Method: service_json
Error: API returned: sample_rate_hertz (16000) in RecognitionConfig must either be omitted or match the value in the WAV header ( 8000).

Please can you help

**Comment by MarkEdmondson1234** [comment]
I can't see the code you are using, I guess perhaps you are specifying the sample rate in your audio sample?  Try not supplying it, or if you must then this section covers everything you need to know about how to encode the audio so it works https://cloud.google.com/speech/docs/encoding

**Comment by MarkEdmondson1234** [comment]
It defaults to `sampleRateHertz=16000` so try supplying 8000 instead:

```r
gl_speech(audio_file, sampleRateHertz=8000L)
```

**Comment by davRuser** [comment]
hi all,

I try this code

gl_speech("test.wav")

and i get:

"Request failed [400]. Retrying in 1 seconds...
Request failed [400]. Retrying in 2.5 seconds...
2018-03-05 11:57:40> Request Status Code: 400
Scopes: https://www.googleapis.com/auth/cloud-platform
App key: 564266350373-q5ggqe4k894orbfbu5nfq85g1dafvnl9.apps.googleusercontent.com
Method: new_token
Error: API returned: sample_rate_hertz (48000) in RecognitionConfig must either be omitted or match the value in the WAV header ( 44100)."

any ideas?

many thanks
David

**Comment by MarkEdmondson1234** [comment]
Try supplying the sampleRateHertz:

```r
gl_speech("test.wav", sampleRateHertz=44100L)
```

**Comment by Punitha89** [comment]
Sorry for the delay Mark, I will try sampleRateHertz and update you. But i remember trying this and still i was getting the same error.

**Comment by davRuser** [comment]
with gl_speech("test.wav", sampleRateHertz=44100L) it's doesn't work. what do you think?

**Comment by davRuser** [comment]
I give you my code:
library(tuneR)
library(googleLanguageR)

files<-"test.wav"
readWave(files)

"Wave Object
	Number of Samples:      196608
	Duration (seconds):     4.46
	Samplingrate (Hertz):   44100
	Channels (Mono/Stereo): Stereo
	PCM (integer format):   TRUE
	Bit (8/16/24/32/64):    16 "

gl_speech("test.wav", sampleRateHertz=44100L)

"Request failed [400]. Retrying in 1.8 seconds...
Request failed [400]. Retrying in 1.3 seconds...
2018-03-05 15:31:38> Request Status Code: 400
Scopes: https://www.googleapis.com/auth/cloud-platform
App key: 564266350373-q5ggqe4k894orbfbu5nfq85g1dafvnl9.apps.googleusercontent.com
Method: new_token
Error: API returned: Must use single channel (mono) audio, but WAV header indicates 2 channels."

# I use very simple wave files, I record my voice for 5 sec.

any help please?
thx
David

**Comment by MarkEdmondson1234** [comment]
Ah yeah I tried to do similar with tuneR before, the problem I think is that its a stereo file.

If you check out https://github.com/ropensci/googleLanguageR/blob/master/inst/shiny/capture_speech/server.R you can see how I got around it.

The pertinent bit, to create a valid WAV file is here:

```r
    ## split two channel audio
    audio_split <- length(a)/2
    a1 <- a[1:audio_split]
    a2 <- a[(audio_split+1):length(a)]

    # construct wav object that the API likes
    Wobj <- Wave(a1, a2, samp.rate = 44100, bit = 16)
    Wobj <- normalize(Wobj, unit = "16", pcm = TRUE)
    Wobj <- mono(Wobj)

    wav_name <- paste0("audio",gsub("[^0-9]","",Sys.time()),".wav")

writeWave(Wobj, wav_name, extensible = FALSE)
```

**Comment by davRuser** [comment]
a is readWave?
what is Wave() function?

**Comment by davRuser** [comment]
Any help?

**Comment by MarkEdmondson1234** [comment]
Please stick to one issue per thread so I can keep track https://github.com/ropensci/googleLanguageR/issues/34
