### ISSUE TITLE
Error returned for gl_speech_op()

### ISSUE THREAD

**Issue by smmurphy** [ropensci/googleLanguageR#30]
First, thank you so much for your work on this package!  I have been using this very successfully on roughly 5 minute files with the following:

```
op <- gl_speech("file",
          encoding = "FLAC",
          sampleRateHertz = 48000L,
          speechContexts = list(phrases = hints)$transcript,
          asynch = TRUE)
text <- gl_speech_op(op)
```
I just tried with a longer file, 45 minutes, using the same code as above and received the following:

```
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
Warning message:
In call_api() :
  API Data failed to parse.  Returning parsed from JSON content.
                    Use this to test against your data_parse_function.
```

I verified that the above code still works perfectly well on the 5 minute files I was working with previously.  Any idea what might be going on?

**Comment by MarkEdmondson1234** [comment]
Thanks @smmurphy - I have never tried it on an audio file that long, so will need to check it to reproduce.  That error is when the API response is unexpected format, so perhaps its empty or with a message saying something like "Your file is too large" - nevertheless it would be good to track down, will take a closer look.

**Comment by smmurphy** [comment]
Thanks for looking into this @MarkEdmondson1234 .  I got a little further with this... what I did is regenerate `call_api()` with the parse function as: `parse_async` instead of `parse_op`.  This initially threw an error due to the if statement:

```
if(!is.null(x$metadata$startTime)){
    my_message("Speech transcription running - started at ", x$metadata$startTime,
               " - last update: ", x$metadata$lastUpdateTime, level = 3)
  }
```
So I made a local copy of the function that was just...
```
# parse asynchronous speech calls responses
parse_async <- function(x) {
  structure(x, class = "gl_speech_op")
}
```
Running that returned the request (though not in as convenient a format).

I'm not sure exactly why, likely something to do with metadata handling, but it appears that `parse_op` is defaulting to `parse_speech`, which is what I was getting for the 5 minute files and working.  For the longer file it still defaults to `parse_speech`, but that fails whereas `parse_async` works.

**Comment by MarkEdmondson1234** [comment]
Thans @smmurphy that is exactly what I would have done - it would be really useful if you can report the results of `str(x)` of the object you get with your local copy of `parse_async()` - then I can modify the existing one to be more forgiving and accept the response you are getting.  It sounds odd, that in your case the `x$metadata$startTime` isn't present, but a quick enough fix to make it conditional.
