### ISSUE TITLE
issue with gl_speech() function

### ISSUE THREAD

**Issue by davRuser** [ropensci/googleLanguageR#34]
Hi all,

I use the following code:

```r
gl_speech("test.wav")
```
I get:

```
"Request failed [400]. Retrying in 1 seconds...
Request failed [400]. Retrying in 2.5 seconds...
2018-03-05 11:57:40> Request Status Code: 400
Scopes: https://www.googleapis.com/auth/cloud-platform
App key: 564266350373-q5ggqe4k894orbfbu5nfq85g1dafvnl9.apps.googleusercontent.com
Method: new_token
Error: API returned: sample_rate_hertz (48000) in RecognitionConfig must either be omitted or match the value in the WAV header ( 44100)."
```
any ideas?

many thanks
David

and when supplying sample rate:

```
gl_speech("test.wav", sampleRateHertz=44100L)
Request failed [400]. Retrying in 1.8 seconds...
Request failed [400]. Retrying in 1.3 seconds...
2018-03-05 15:31:38> Request Status Code: 400
Scopes: https://www.googleapis.com/auth/cloud-platform
App key: 564266350373-q5ggqe4k894orbfbu5nfq85g1dafvnl9.apps.googleusercontent.com
Method: new_token
Error: API returned: Must use single channel (mono) audio, but WAV header indicates 2 channels.
```

and then..

what is Wave() function?
I get Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function ‘Wave’ for signature ‘"Wave"’

**Comment by MarkEdmondson1234** [comment]
Audio encoding is a complicated subject, take a look here https://cloud.google.com/speech/docs/encoding

But in essence you need mono, no-extensible wav audio to work, or look at the other formats such as FLAC.

An example is in the Shiny app, if you are using `tuneR` to input your audio.

```r
library(tuneR)

a <- input_audio()

    ## split two channel audio
    audio_split <- length(a)/2
    a1 <- a[1:audio_split]
    a2 <- a[(audio_split+1):length(a)]

    # construct wav object that the API likes
    Wobj <- Wave(a1, a2, samp.rate = 44100, bit = 16)
    Wobj <- normalize(Wobj, unit = "16", pcm = TRUE)
    Wobj <- mono(Wobj)

    wav_name <- paste0("audio",gsub("[^0-9]","",Sys.time()),".wav")

    writeWave(Wobj, wav_name, extensible = FALSE)
```

**Comment by MarkEdmondson1234** [comment]
The `Wave()` function is from `tuneR` which is one choice for audio in R, please refer to its help for details on the functions.

The example above takes stereo wav audio, makes it mono and normalises the volume so that it will work through the API, as an example, but it will depend on your audio file and how it is recorded and encoded on what will work for you.

**Comment by davRuser** [comment]
your exemple do not work with simple .Wav files:

Wave Object
	Number of Samples:      196608
	Duration (seconds):     4.46
	Samplingrate (Hertz):   44100
	Channels (Mono/Stereo): Stereo
	PCM (integer format):   TRUE
	Bit (8/16/24/32/64):    16 

I just need help on this exemple

**Comment by MarkEdmondson1234** [comment]
Start by turning your wav file into mono.

**Comment by davRuser** [comment]
hi,

thanks for your asnwer, the code is ok:

files<-"test.wav"
a<-readWave(files)
a<-mono(a, which = c("left", "right", "both"))
writeWave(a, "test2.csv", extensible = F)
a<-readWave("test2.csv")
gl_speech("test2.csv",sampleRateHertz=44100L,languageCode = "fr-FR")

"$transcript
# A tibble: 1 x 2
                            transcript confidence
                                 <chr>      <chr>
1 "<ff><fe>oui allô bonjour<ff><fe>"  0.9752539

$timings
  startTime endTime    word
1    0.100s  1.300s     oui
2    1.300s  1.600s    allô
3    1.600s  1.700s bonjour"

but why do you split into a1/a2?

thx
David

**Comment by MarkEdmondson1234** [comment]
Glad its working.  For my test file, the stereo file was arranged that left channel was the first half of the file, the right channel was the second half, so I had to split them and rebuild, then turn to mono.  Its tricky to give one definitive answer as sound files are recorded in lots of different formats.

**Comment by davRuser** [comment]
thx Mark.

you know how to change the bit on a .wav files?

**Comment by MarkEdmondson1234** [comment]
Not through R, I use audio programs such as Audacity to manipulate audio files generally though, probably easiest way.

**Comment by davRuser** [comment]
ok I understand, because I try with another files and it does not work with 8 bit (only 16). But I don't want to do that manualy...
David

**Comment by davRuser** [comment]
hi,

I test on other files:

a<-readWave("bush.wav")
a<-tuneR::normalize(a, unit = "16", pcm = TRUE, center=TRUE, rescale=TRUE)
writeWave(a, "bush1.wav", extensible = F)
a<-readWave("bush1.wav")
test<-gl_speech("bush1.wav",sampleRateHertz=11025L)
 I get

"   startTime endTime        word
1     1.600s      3s           I
2         3s  3.300s       pride
3     3.300s  3.400s      myself
4     3.400s  3.900s          on
5     3.900s      5s           a
6         5s  5.400s     prudent
7     5.400s  5.400s         man
8     5.400s  5.800s           I
9     5.800s  6.100s     believe
10    6.100s  6.200s        that
11    6.200s  6.700s    patience
12    6.700s  6.800s          is
13    6.800s  6.900s           a
14    6.900s  7.300s      virtue
15    7.300s  8.100s         but
16    8.100s  8.200s           I
17    8.200s  8.800s  understand
18    8.800s  8.900s         the
19    8.900s 14.900s        lack
20   14.900s 15.100s          of
21   15.100s 15.700s improvement
22   26.300s 26.700s          is
23   26.700s 26.800s         the
24   26.800s 27.100s  well-being
25   27.100s 27.300s          of
26   27.300s 27.400s         our
27   27.400s 27.900s     country"

I see a huge cut on line 21,

so I do not read all the wav files. My files is

"Wave Object
	Number of Samples:      314358
	Duration (seconds):     28.51
	Samplingrate (Hertz):   11025
	Channels (Mono/Stereo): Mono
	PCM (integer format):   TRUE
	Bit (8/16/24/32/64):    16 "

thx
David

**Comment by MarkEdmondson1234** [comment]
I think you need to listen to the file and see if your processing did something weird.  I don't know much about audio processing in R since I usually use an audio editor, you may have a more knowledge answer if you ask on `tuneR`'s issue thread (I am interested too)

**Comment by PranavPable** [comment]
I am getting this error on passing a wav file into readwave function.
**API returned: WAV header indicates an unsupported format.**

**Comment by MarkEdmondson1234** [comment]
Please see the link in the first reply to diagnose audio file encoding problems, I can’t help much as it’s a broad issue.
