### ISSUE TITLE
Issue with error code 403

### ISSUE THREAD

**Issue by lohithmc44** [ropensci/googleLanguageR#35]
@Any suggestions on how to solve this issue. I am getting the following error in R:

Listening on http://127.0.0.1:7522
Calling Speech API
Request failed [403]. Retrying in 1.7 seconds...
Request failed [403]. Retrying in 3.7 seconds...
2018-03-05 22:27:42> Request Status Code: 403
Scopes: https://www.googleapis.com/auth/cloud-platform
Method: service_json
Warning: Error in : API returned: Google Cloud Speech API has not been used in project cool-bay-197110 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/speech.googleapis.com/overview?project=cool-bay-197110 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. @MarkEdmondson1234

**Comment by MarkEdmondson1234** [comment]
Follow the advice of the error message :) click the link, activate the api and retry.
