### ISSUE TITLE
Error: API returned: sample_rate_hertz (16000)

### ISSUE THREAD

**Issue by dataning** [ropensci/googleLanguageR#38]
Hi Mark, 

I was trying to run some basic voice memo transcribing through the package. But I keep getting this error. 

`test_audio <- "gen.wav"`
`gl_speech(test_audio)$transcript`

`Error: API returned: sample_rate_hertz (16000) in RecognitionConfig must either be omitted or match the value in the WAV header ( 48000).`

What's the best way to set the parameter to overcome this?

**Comment by MarkEdmondson1234** [comment]
Add it via the `sampleRateHertz` argument e.g.

```r
gl_speech(test_audio, sampleRateHertz = 48000L)$transcript
```

**Comment by dataning** [comment]
Thanks Mark. 

I found the problem had something to do with the duration of the sound file - it's over 1 minute. So I have uploaded the file to the cloud bucket and put the link into first parameter. I have listed the syntax below and the file is [in public](https://storage.cloud.google.com/6pokemon/gen.wav). At the moment, the return is "NULL" - very interesting. 

```
gl_speech("gs://6pokemon/gen.wav", encoding = "LINEAR16", sampleRateHertz = 48000L, asynch = TRUE)$transcript
gl_speech("gs://6pokemon/gen.flac", encoding = "FLAC", sampleRateHertz = 48000L, asynch = TRUE)$transcript
```

Have you got any examples trying to translate a wav/flac file, which is more than 2 or 3 minutes - like a song's length)?

**Comment by MarkEdmondson1234** [comment]
I just fixed that a second ago in this commit https://github.com/ropensci/googleLanguageR/commit/e36411044ecb896738d43a4b6fe38eeb57f93b5e , if you download the latest GitHub version - for long running it should return an async object, which you then feed into `gl_speech_op()` that will return your data once finished

**Comment by MarkEdmondson1234** [comment]
That is setting it back to what is documented here http://code.markedmondson.me/googleLanguageR/articles/speech.html   I think it got overwritten in a recent pull, sorry about that.

**Comment by dataning** [comment]
Everything is working fine now! Thanks Mark!

**Comment by dataning** [comment]
Sorry, one remaining issue - I tried a 15 minutes wav file and it keeps coming back with the API Data failed message. I have read some previous closed threads who had a similar issue. What's the best way to overcome this? 

`async <- gl_speech("gs://6pokemon/buzzfeed.wav", sampleRateHertz = 44100L, asynch = TRUE)`
`result <- gl_speech_op(async)`

```
Error in data_parse_function(req$content, ...) : object 'out' not found
Warning message:
In call_api() :
  API Data failed to parse.  Returning parsed from JSON content.
                    Use this to test against your data_parse_function.
```

**Comment by MarkEdmondson1234** [comment]
Try again now with the latest version (and thanks for the test file)

```r
gl_speech("gs://6pokemon/buzzfeed.wav", sampleRateHertz = 44100L, asynch = TRUE)
gl_speech_op(.Last.value)
2018-03-22 16:44:22 -- - started at 2018-03-22T15:39:25.442136Z - last update: 2018-03-22T15:44:09.817086Z
## Send to gl_speech_op() for status
## 3081429970242452248
gl_speech_op(.Last.value)
2018-03-22 16:45:11 -- Asychronous transcription finished.
....
```

It took about 5 mins to transcribe

**Comment by dataning** [comment]
It worked magically and yes, I can confirm that it has taken 5 minutes to convert a 15-minutes wav file.

**Comment by MarkEdmondson1234** [comment]
Party :)

**Comment by AdhishiP** [comment]
Hello, Im trying to run a wav fileand I'm continuously getting this error. What to do?
Error: API returned: Must use single channel (mono) audio, but WAV header indicates 2 channels

**Comment by MarkEdmondson1234** [comment]
@AdhishiP please don't comment on closed issues, open a new one, although in your case it looks like this issue may help you: https://github.com/ropensci/googleLanguageR/issues/34
