### ISSUE TITLE
Speaker diarization would be extremely welcome in an R package

### ISSUE THREAD

**Issue by kgarnick** [ropensci/googleLanguageR#40]
I currently have to wrap Python to do it, but would love to see it in your/some R package in the future!

**Comment by MarkEdmondson1234** [comment]
Is that a feature of the Google APIs or something else?  I'd love to see an example if possible.

**Comment by kgarnick** [comment]
I don't think Google Cloud offers diarization. I've been using the segmentation script from [pyAudioAnalysis](https://github.com/tyiannak/pyAudioAnalysis).

**Comment by MarkEdmondson1234** [comment]
It may be possible via [`reticule`](https://github.com/rstudio/reticulate)

**Comment by MarkEdmondson1234** [comment]
I think this is something that would be in another package, if the APIs don't offer it.

**Comment by MarkEdmondson1234** [comment]
This is in the API now, so will happen https://github.com/ropensci/googleLanguageR/issues/47
