### ISSUE TITLE
Document uploaded to Cloud Storage when: 'Inline audio exceeds duration limit' on `asynch = T` calls

### ISSUE THREAD

**Issue by cabrokiller** [ropensci/googleLanguageR#42]
I had the following error when trying to do an asynch call. @Bellman281 reported this issue [here](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1414). Did the google API change?

```
asynch <- gl_speech("data/TEMP/CPC.wav", asynch = T, languageCode = "es-ES")

Request failed [400]. Retrying in 1 seconds...
Request failed [400]. Retrying in 1.9 seconds...
2018-06-12 00:00:44> Request Status Code: 400
Scopes: https://www.googleapis.com/auth/cloud-platform
Method: service_json
Error: API returned: Inline audio exceeds duration limit. Please use a GCS URI.
```

**Comment by MarkEdmondson1234** [comment]
Is the audio longer than 60 seconds? Also did you try with CRAN and GitHub version?

**Comment by cabrokiller** [comment]
I tried the CRAN version (1.1.0) and the github version, both ave the same error.  The audio is a 16000 hz wav of +- 3 minutes.

**Comment by MarkEdmondson1234** [comment]
Ok then I think this is working as expected, but perhaps documentation is needed to be clearer - you should upload the audio file to Google Cloud Storage yourself, get the `gs://` URL and put that in as the first argument.  This can be done via the Google Cloud Storage Web UI or via `googleCloudStorageR`.  

I will look at making this clearer, and perhaps ultimately also make the function upload this for you via a `googleCloudStorageR` dependency.

**Comment by cabrokiller** [comment]
I see, thanks for the clarification!

**Comment by dsaada** [comment]
Hi All,

I try to run the following code

`files<-"test2.wav"
readWave(files)

gcs <- gl_speech(files, asynch = F)
gl_speech_op(gcs)`

my audio is 

> Wave Object
	Number of Samples:      2377728
	Duration (seconds):     148.61
	Samplingrate (Hertz):   16000
	Channels (Mono/Stereo): Mono
	PCM (integer format):   TRUE
	Bit (8/16/24/32/64):    16

> 

I get the following error:

_API returned: Inline audio exceeds duration limit. Please use a GCS URI._

any help please?
thx
David

**Comment by MarkEdmondson1234** [comment]
Does the answer above help?

**Comment by dsaada** [comment]
I do not understand, I have my audio files in my local environnement, I have to move it in google cloud and call him for the API?

**Comment by MarkEdmondson1234** [comment]
Yes that’s it.

**Comment by MarkEdmondson1234** [comment]
If longer than 60 seconds. You can use googleCloudStorageR

**Comment by dsaada** [comment]
I have o project on google cloud, and googleAuthR::gar_auth(). How can I do to input audio files on google cloud please?

**Comment by MarkEdmondson1234** [comment]
You can upload it directly in the browser using the web UI for google Cloud Storage, or programmatically via googleCloudStorageR. See it’s website for details.

**Comment by dsaada** [comment]
ok i will try. thx

**Comment by dsaada** [comment]
Hi Mark,

it'sd not possible to make a release and use the API with local files? it's looks like pretty difficult to use googlestorage with R.

**Comment by MarkEdmondson1234** [comment]
Sorry, that’s the only option Google offers for files larger than 60 seconds.

**Comment by dsaada** [comment]
Or can we cut the audio files for example in sequences of 5 sec and run a loop?

**Comment by MarkEdmondson1234** [comment]
Well 55 seconds is probably better but yes you can do that.

**Comment by dsaada** [comment]
I will explore all solution and make a post on it.

**Comment by cainesap** [comment]
For anyone else who finds this like I did from googling the same error message as OP, here are the steps I took to reach a solution:

1, install googleCloudStorageR https://cran.r-project.org/web/packages/googleCloudStorageR/vignettes/googleCloudStorageR.html
2, set GCS_AUTH_FILE as described in the vignette; n.b. you can use the same json file as you presumably already downloaded for googleLanguageR
3, note the storage pricing here https://cloud.google.com/storage/pricing
4, create a bucket in the GCS JSON API browser https://console.cloud.google.com/storage/browser 
5, choose the 'object-level' access control option
6, now you can set your default bucket with gcs_global_bucket() and/or in .Renviron
7, upload your soundfile: `gcs_upload(mysound)`
8, the URI for the above example will be: `guri <- 'gs://<bucketname>/mysound'`
9, then `async <- gl_speech(guri, languageCode=mylang, sampleRateHertz=myrate, asynch=T)`
10, Sys.sleep() for a bit (or more robustly, write a while loop)
11, get result: `speech <- gl_speech_op(async)`
12, optionally clean up your bucket: `gcs_delete_object('mysound')`

This may not be the only way, or the right way, but it worked for me.
Thanks Mark for writing and maintaining both libraries! They're proving very valuable right now :)
