### ISSUE TITLE
Implement Enable Automatic Punctuation 

### ISSUE THREAD

**Issue by eric-kruger** [ropensci/googleLanguageR#48]
Hi Mark,

Would it also be possible to [enable Automatic Punctuation](https://cloud.google.com/speech-to-text/docs/automatic-punctuation) in future releases of `googleLanguageR`?

Thanks,
Eric

**Comment by MarkEdmondson1234** [comment]
Yep this too.  I look to include the beta features on the dev version on GitHub, then once they are out of beta move it into the CRAN version.

**Comment by simitpatel** [comment]
I came to request this also. Mark, truly awesome packages -- thank you very, very much for sharing. I'm going to look through your code a bit more, hopefully I can submit some useful pull requests to help development.

**Comment by MarkEdmondson1234** [comment]
See https://github.com/ropensci/googleLanguageR/issues/47 for discussion

The example in this case would be:

```r
## Use a custom configuration
my_config <- list(enableAutomaticPunctuation = TRUE)

# languageCode is required, so will be added if not in your custom config
gl_speech(my_audio, languageCode = "en-US", customConfig = my_config)
```
