### ISSUE TITLE
Error: Path '' does not exist

### ISSUE THREAD

**Issue by johnfrombluff** [ropensci/googleLanguageR#50]
Firstly, thanks!  You've done a great service to the R community by providing this package. But sadly, I can't get it to work. After restarting the R session in RStudio:

`
Welcome at Tue Sep 25 11:43:39 2018 

> Sys.setenv(GL_AUTH = "/home/john/Dropbox/Writing/Software/Go/src/snp/google-service-account.json")
> googleLanguageR::gl_auth("~/Dropbox/Writing/Software/Go/src/snp/google-service-account.json")
> library(googleLanguageR)
> test_audio <- system.file("~/Documents/test-for-google.flac", package = "googleLanguageR")
> result <- gl_speech(test_audio, languageCode = "en-GB")
Error: Path '' does not exist`

Maybe this will help?

`
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 28 (Workstation Edition)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleLanguageR_0.2.0

loaded via a namespace (and not attached):
 [1] digest_0.6.17     crayon_1.3.4      assertthat_0.2.0  R6_2.2.2          jsonlite_1.5      magrittr_1.5     
 [7] pillar_1.3.0      httr_1.3.1        rlang_0.2.2       curl_3.2          rstudioapi_0.7    googleAuthR_0.6.3
[13] tools_3.5.0       purrr_0.2.5       yaml_2.2.0        compiler_3.5.0    base64enc_0.1-3   memoise_1.1.0    
[19] openssl_1.0.2     tibble_1.4.2     
`

**Comment by MarkEdmondson1234** [comment]
Its saying the `GL_AUTH` environment is not set which is strange if you set it the line before.  Try putting it in `.Renviron` file in the working directory or your user home directory.

You should then just need one of these methods:

1. Downloaded the `.json` file
2. Load library `library(googleLanguageR)`
3. Authenticate using `gl_auth(path_to_json_file)`

Or this one:

1. Download json file
2. Put json file in environment argument `GL_AUTH` (Via `.Renviron` file or otherwise)
3. Load library (`library(googleLanguageR)`)

It looks like you are conflating the two methods a bit in your examples.  

Also the library needs to be loaded, so using `googleLanguageR::ga_auth()` may not put it in the library environment it needs.  Lastly I have had some trouble with Dropbox synching so try it out of that folder. 

HTH, Mark

**Comment by johnfrombluff** [comment]
Thanks very much for your quick and helpful reply, Mark!

Unfortunately the issue persists. I put the line in my ~/.Renviron file, as you instructed. The gl_nlp() function works fine, but the gl_speech() function does not. After `rm(list=ls(all.names=TRUE))` and restarting the R session:

`
 passage <- "Did you consider an airbnb ? I got something hooked into a little bit forward. Just never go. Just big risk adverse if something went wrong, something like without having my balls and some active over a year and stuff. So contacting people for being a little bit difficult to your security and ours. Jesus, he's. Sure. Okay. Okay. It sounds great. We're about to traveling to japan and doing a couple of days here. I like it here"
> library(googleLanguageR)
Successfully authenticated via /home/john/Documents/google-service-account.json
> nlp_result <- gl_nlp(passage)
2018-09-26 09:31:33 -- annotateText: 429 characters
> test_audio <- system.file("/home/john/Documents/test-for-google.flac", package = "googleLanguageR")
> speech_result <- gl_speech(test_audio, languageCode = "en-GB")
Error: Path '' does not exist
`

**Comment by MarkEdmondson1234** [comment]
Don’t put your audio filepath in system.file() - that is only to take the example file included with the package. You can send in the filepath as is.

**Comment by johnfrombluff** [comment]
Awesome! Thanks heaps, Mark. It's working fine now. Thanks again for the fine package, as well as the timely help!
