### ISSUE TITLE
How to get Authentication?

### ISSUE THREAD

**Issue by englianhu** [ropensci/googleLanguageR#51]
> **Authentication**
The best way to authenticate is to use an environment file. See ?Startup. I usually place this in my home directory. (e.g. if using RStudio, click on Home in the file explorer, create a new TEXT file and call it .Renviron)
Set the file location of your download Google Project JSON file in a GL_AUTH argument:
>```
>GL_AUTH=location_of_json_file.json
>```
I try to browse over http://code.markedmondson.me/googleLanguageR/articles/speech.html but don;t know how to get authentication in order to use the functions.
```r
> library('googleLanguageR')
> lnk <- 'https://scontent-yyz1-1.xx.fbcdn.net/v/t66.18014-6/42832823_1854945517918295_8803608342512894293_n.mp4?_nc_cat=110&efg=eyJ2ZW5jb2RlX3RhZyI6Im9lcF9oZCJ9&oh=08e0a1bce580184048cd33489d3c254c&oe=5C3DAE2F'
> vfile <- tempfile()
> 
> if (file.exists(vfile)) {
+   vday <- gl_speech(vfile)
+   
+   play(vday)
+ } else {
+   download.file(lnk, vfile, mode = 'wb')
+   vday <- gl_speech(vfile)
+   #play(vday)
+ }
trying URL 'https://scontent-yyz1-1.xx.fbcdn.net/v/t66.18014-6/42832823_1854945517918295_8803608342512894293_n.mp4?_nc_cat=110&efg=eyJ2ZW5jb2RlX3RhZyI6Im9lcF9oZCJ9&oh=08e0a1bce580184048cd33489d3c254c&oe=5C3DAE2F'
Content type 'video/mp4' length 5844502 bytes (5.6 MB)
downloaded 5.6 MB

2018-10-18 22:42:25> No authorization yet in this session!
2018-10-18 22:42:25> NOTE: a  .httr-oauth  file exists in current working directory.
 Run authentication function to use the credentials cached for this session.
Error: Invalid token
```

**Comment by MarkEdmondson1234** [comment]
You need to follow the [Installation steps](http://code.markedmondson.me/googleLanguageR/index.html#installation) to generate a service credential JSON file in a Google console.

**Comment by MarkEdmondson1234** [comment]
There is a [YouTube video](https://www.youtube.com/watch?v=zgwDQu-mCOc) showing how to do it for googleAnalyticsR, but a very similar process

**Comment by james-henderson93** [comment]
hey Mark,

I am having a similar problem with googleLanguageR. 

**_2019-12-02 10:07:45> No authorization yet in this session!
2019-12-02 10:07:45> No  .httr-oauth  file exists in current working directory.  Do library authentication steps to provide credentials.
 Error: Invalid token_** 

> library(googleAnalyticsR)
> ga_auth("ga.oauth")
2019-12-02 10:26:28> Default Google Project for googleAnalyticsR is set.  
 This is shared with all googleAnalyticsR users. 
 If making a lot of API calls, please: 
 visit: https://bit.ly/2Evk6hn 
 for instructions on setting your own Google Project 

Error: Path 'ga.oauth' does not exist


I have my json file and api key but for some reason I cannot get this authorised. 

any help would be great, thanks.

**Comment by MarkEdmondson1234** [comment]
Could you open this on `googleAnalyticsR` repo? 
https://github.com/MarkEdmondson1234/googleAnalyticsR

But looks like you need to review the setup guide on the website: https://code.markedmondson.me/googleAnalyticsR/articles/setup.html

**Comment by james-henderson93** [comment]
yep but when using ga_auth() it takes me to the google webpage with an error.

400. That’s an error.

Error: invalid_request
Missing required parameter: client_id
Learn more
Request Details
That’s all we know.

**Comment by MarkEdmondson1234** [comment]
Ok looks like we need to see all your code you are attempting.  Please open the issue on https://github.com/MarkEdmondson1234/googleAnalyticsR not here on https://github.com/ropensci/googleLanguageR
