### ISSUE TITLE
Possible issue with asynch call?

### ISSUE THREAD

**Issue by xazip** [ropensci/googleLanguageR#72]
I am working with a 10 min wav file that contains a conversation between two individuals. 

![cloud_help](https://user-images.githubusercontent.com/42751011/84320899-fdedea00-ab37-11ea-9647-45c8c63b0883.PNG)

**Comment by MarkEdmondson1234** [comment]
For certain size files it needs to be a Cloud Storage location `gs://bucket/file.wav` - its not clear where that boundary is though.  But try uploading your file in the web console or using `googleCloudStorageR`

**Comment by xazip** [comment]
Thanks!
