### ISSUE TITLE
gl_speech request almost always times out, no proper error message

### ISSUE THREAD

**Issue by iamserious** [ropensci/googleLanguageR#73]
First of all, thank you for maintaining this project.

I have some voice recordings that I want to transcribe with gcloud speech-to-text. Unfortunately my R almost always hangs up, or the request times out, when I send a request with gl_speech. Thereby it doesn't matter if I simply run your example code, or if I use my own audio files instead.

```r
library(googleLanguageR)
gl_auth("XXXX.json")
test_audio <- system.file("woman1_wb.wav", package = "googleLanguageR")
gl_speech(test_audio, languageCode = "en-GB")
```

As a Result I only get the following error message:

> 2020-07-02 10:29:39 > Request Status Code:  408
> Error : lexical error: invalid char in json text.
>                                        <!DOCTYPE html> <html lang=en> 
>                      (right here) ------^
> 
> <!DOCTYPE html>
> <html lang=en>
>   <meta charset=utf-8>
>   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
>   <title>Error 408 (Request Timeout)!!1</title>
>   <style>
>     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
>   </style>
>   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
>   <p><b>408.</b> <ins>That’s an error.</ins>
>   <p>Your client has taken too long to issue its request.  <ins>That’s all we know.</ins>
> Error: lexical error: invalid char in json text.
>                                        <!DOCTYPE html> <html lang=en> 
>                      (right here) ------^

Do you have any I ideas how to fix that, or what could be the underling problem?
Best 
Michael

**Comment by MarkEdmondson1234** [comment]
Looks like something underlying the API or library, are you behind a proxy perhaps?  Perhaps check that the authentication process is correct by running some of the other functions such as `gl_translate()` examples. If you run the code with `options(googleAuthR.verbose=2)` we will get a bit more logging info to try and deduce what is happening.

**Comment by iamserious** [comment]
Whoah. what a fast answer.

Nop I'm not behind a proxy. Will Check the more verbosed output first.

**Comment by iamserious** [comment]
Ok with the verbosed output I'm getting:


>  gl_speech(test_audio)$transcript
> ℹ 2020-07-02 10:48:05 > Token exists.
> ℹ 2020-07-02 10:48:05 > Request:  https://speech.googleapis.com/v1/speech:recognize/
> ℹ 2020-07-02 10:48:05 > Body JSON parsed to:  {"config":{"encoding":"LINEAR16","sampleRateHertz":16000,"languageCode":"en-US","maxAlternatives":1,"profanityFilter":false,"speechContexts":{},"enableWordTimeOffsets":true},"audio":{"content": [base code audio i think]

and after that nothing happens.

Will check the other apis but have to enable them first.

**Comment by iamserious** [comment]
Ok I tried it out with gl_translate and that works flawlessly:

> gl_translate(text, target = "da")$translatedText
> 2020-07-02 10:55:58 -- Translating text: 114 characters - 
> ℹ 2020-07-02 10:55:58 > Token exists.
> ℹ 2020-07-02 10:55:58 > Request:  https://translation.googleapis.com/language/translate/v2/
> [1] "at administrere medicin til dyr er ofte en meget vanskelig sag, og alligevel er det undertiden nødvendigt at gøre det"
> > ## translate British into Danish 

It seems to have something to do with the speech to text api.

**Comment by MarkEdmondson1234** [comment]
Hmm ok thanks, it looks ok so nothing obvious, I'll investigate, perhaps test the example audio just in case.  

One thing you may try also is use another PC or rstudio.cloud to see if you get the same issue, to see if we can see if its something to do with your setup.

**Comment by iamserious** [comment]
Good Idea will change to the setup of my colleague.

FYI:
I tried it wit R 4.0.2 as well as 3.6.3. R-studio version is 1.3.959

**Comment by MarkEdmondson1234** [comment]
Could you also report your `sessionInfo()` ?  Mine is below, which I've confirmed works with the code in your issue:

```r
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleLanguageR_0.3.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6           rstudioapi_0.11        googleAnalyticsR_0.8.0
 [4] magrittr_1.5           tidyselect_1.1.0       R6_2.4.1              
 [7] rlang_0.4.6            fansi_0.4.1            httr_1.4.1            
[10] dplyr_1.0.0            tools_3.6.3            packrat_0.5.0         
[13] utf8_1.1.4             cli_2.0.2              withr_2.1.2           
[16] googleAuthR_1.3.0      askpass_1.1            cranlogs_2.1.1        
[19] ellipsis_0.3.0         openssl_1.4.1          assertthat_0.2.1      
[22] digest_0.6.25          tibble_3.0.0           gargle_0.4.0          
[25] lifecycle_0.2.0        crayon_1.3.4           tidyr_1.0.2           
[28] purrr_0.3.3            base64enc_0.1-3        vctrs_0.3.1           
[31] fs_1.4.1               curl_4.3               memoise_1.1.0         
[34] glue_1.4.1             compiler_3.6.3         pillar_1.4.3          
[37] generics_0.0.2         jsonlite_1.6.1         pkgconfig_2.0.3
```

**Comment by iamserious** [comment]
My Session info:

> > sessionInfo()
> R version 3.6.3 (2020-02-29)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS Catalina 10.15.5
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] googleLanguageR_0.3.0
> 
> loaded via a namespace (and not attached):
>  [1] magrittr_1.5      R6_2.4.1          rlang_0.4.6       fansi_0.4.1       httr_1.4.1        tools_3.6.3       cli_2.0.2        
>  [8] googleAuthR_1.3.0 askpass_1.1       ellipsis_0.3.1    openssl_1.4.2     assertthat_0.2.1  digest_0.6.25     tibble_3.0.1     
> [15] gargle_0.5.0      lifecycle_0.2.0   crayon_1.3.4      purrr_0.3.4       base64enc_0.1-3   vctrs_0.3.1       fs_1.4.2         
> [22] curl_4.3          memoise_1.1.0     glue_1.4.1        compiler_3.6.3    pillar_1.4.4      jsonlite_1.7.0    pkgconfig_2.0.3

**Comment by iamserious** [comment]
Ok I tried it out on my colleagues machine, same result :(

> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.15.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
  [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
  [1] googleLanguageR_0.3.0

loaded via a namespace (and not attached):
  [1] Rcpp_1.0.3        fansi_0.4.1       digest_0.6.16     crayon_1.3.4      assertthat_0.2.0 
[6] R6_2.2.2          jsonlite_1.6.1    magrittr_1.5      pillar_1.4.3      httr_1.4.1       
[11] rlang_0.4.5       cli_2.0.2         curl_3.2          rstudioapi_0.11   fs_1.3.2         
[16] googleAuthR_1.3.0 tools_3.5.1       glue_1.3.0        purrr_0.3.3       yaml_2.2.0       
[21] compiler_3.5.1    askpass_1.1       pkgconfig_2.0.2   base64enc_0.1-3   gargle_0.5.0     
[26] memoise_1.1.0     openssl_1.4.1     tibble_2.1.3    


Still a time out error. I also tried every step, routing my traffic over an vpn (to make sure it is not a internet problem) but didn't change anything.

**Comment by MarkEdmondson1234** [comment]
Hmm really don't know where to start sorry, you have the same setup as me and the auth works for other services - I can only think its some kind of firewall or network issue if you are using the same connection as your colleague.

**Comment by iamserious** [comment]
Example audio file also works with out problems. Checked that now.

**Comment by MarkEdmondson1234** [comment]
Oh the example audio file works, but the audio file you are trying doesn't?  In that case it must be the audio encoding of the file?

**Comment by MarkEdmondson1234** [comment]
Does your file work on the website demo? https://cloud.google.com/speech-to-text

**Comment by iamserious** [comment]
Nop, the example files work if played in quicktime. 

In general I don't get the error every time. Every now and than (maybe in 5% of the cases) I also got the text back from the gl_speech call

**Comment by MarkEdmondson1234** [comment]
Ok so the example audio file works 5% of cases?

But the audio file you are trying to transcribe never works?

It says to me its network connection issues, it is uploading a big chunk of audio that perhaps your corporate firewall blocks (most of the time) - you could try uploading your audio to Google Cloud Storage instead and using its URI so it has a secure upload.  Also your example audio needs proper encoding (of which there are millions) - if you try the audio in the website perhaps you can see if it accepts it at all.  There is more on audio encoding here: https://cloud.google.com/speech-to-text/docs/encoding

**Comment by iamserious** [comment]
Yes, the example file works in around 5% of the cases and my own files never work.
I coded my own file as wav, but also tried out flac and mp3 before. 

If I try both files (example and my own, both as wav) on the demo webpage the work without any problems (besides asking me if i'm a robot every time).

Actually I don't think the the firewall is a problem. I'm in Home Office at the moment and here I have a standard DSL connection and if I use the VPN, I'm connected with the DFN (German research network) which is by default extremely relaxed in there firewall setting.



I now have tried out the demo webpage with my own audio file and the webpage also fails some times and gives me an "unauthorized" or a "server errror" message.

**Comment by iamserious** [comment]
It really seems to be somehow due to the transmission. I have now uploaded the data to a bucket in the gcloud and now it works. 
I couldn't get it to work directly from the client. In the meantime I would have thought that there was a problem with the encoding of the audio file in json, because my computer was 100% busy on one core while trying to execute the request.

**Comment by MarkEdmondson1234** [comment]
Ok cool, glad its working now at least.  If you want to automate the uploads there is [`cloudyr/googleCloudStorageR`](https://code.markedmondson.me/googleCloudStorageR/) which will give you the URI for use in `gl_speech()`
