### ISSUE TITLE
Entity sentiment shows but document sentiment shows NA

### ISSUE THREAD

**Issue by madilk** [ropensci/googleLanguageR#75]
Hello, 
I'm not sure if this is an issue or it's just me but here goes. Thanks for creating this package.
I'm trying to run Entity sentiment analysis on a column. Here's my API call for it.
`nlp <- gl_nlp(
  cleanData$translatedText,
  nlp_type = "analyzeEntitySentiment",
  type="PLAIN_TEXT",
  language="en"
)`

When I run nlp$entities, I can see entity level sentiment
![google language r entity sentiment](https://user-images.githubusercontent.com/20192415/111882477-498ac980-89cf-11eb-94e1-3e3fe2d35ff4.JPG)

However, when I try nlp$documentSentiment, I see NA's across all my 5 rows of text data
![NA for document level sentiment google language R](https://user-images.githubusercontent.com/20192415/111882516-763ee100-89cf-11eb-973b-4dfc0d2ddd8e.JPG)

Can you pls help me understand why would this be the case? and what can I do to improve my code here? 
Thanks.

**Comment by MarkEdmondson1234** [comment]
What if you send it in as one string? The code looks like it will send in each element in your column individually. Try paste(x, collapse = " ")

**Comment by madilk** [comment]
Hi Mark,
Here's how the output looks when I try paste command. How can I save these as two dataframes? 
1. with sentiment score per entity
2. document level sentiment

Thanks

![git](https://user-images.githubusercontent.com/20192415/111901817-9f08ba00-8a53-11eb-85c5-b74ec1c89f57.JPG)

**Comment by MarkEdmondson1234** [comment]
Ah I meant in the text you send in - what does 

```r
nlp <- gl_nlp(paste(cleanData$translatedText, collapse = " "),
                        nlp_type = "analyzeEntitySentiment", type="PLAIN_TEXT", language="en" )

```

...look like?  It may be that the document sentiment needs a minimum number of letters to work.

**Comment by madilk** [comment]
As per this link [for Classification function], at least 20 tokens are required https://cloud.google.com/natural-language/docs/classifying-text 
2 out 5 rows in my sample data are fairly long. Also when I try the paste command within gl_nlp, I'm getting NA
![doc sentiment](https://user-images.githubusercontent.com/20192415/112025262-70233e80-8b4e-11eb-95f1-25ef2d1de1cd.JPG)
![text length](https://user-images.githubusercontent.com/20192415/112025307-79aca680-8b4e-11eb-93e5-e33f51eaf709.JPG)
