### ISSUE TITLE
googleLanguageR does not translate tweets.

### ISSUE THREAD

**Issue by MRizakis** [ropensci/googleLanguageR#76]
Dear all,
I have recently began utilising the googleLanguageR package in order to translate some tweets. However, while the code runs it does not translate the text column. What is does instead is to produce two additional columns: 1) translated text and 2) source language.
The source language is correct (French). However, the translated column contains the tweets in the original language. I am perplexed as to why this happens. I contacted Mark Edmondson, and he told me to test if I have set up everything properly, buy translating a quote from English to Danish. And it worked. 
Therefore, I am at a loss regarding what I am doing wrong. I had speculated that the format of the corpus is not recognised by the text. Below I have included my code so you can check it out yourselves. I thank you in advance for your help!

```{r}
library(rtweet)
library(tidyverse); theme_set(theme_minimal())
library(quanteda)
library(stm)
library(seededlda)
library(stopwords)
library(stringi)
library(googleLanguageR)
````

```{r}
LePen2020b<-get_timeline("@MLP_officiel",n=3200)

LePen_terrorism_2<-as.data.frame(LePen2020b)

saveRDS(LePen_terrorism_2,"LePen_terrorism_2.rds")
````
```{r}
LePen_Patyb<-readRDS("LePen_terrorism_2.rds")
LePen_2020b<-LePen_Patyb %>% filter(created_at>"2020-09-01",created_at<"2020-12-01")
```

```{r}
LePen_tr_2020<-gl_translate(LePen_Patyb$text, target = "fr", format = c("text"),source = "")
````

And this is where the problem occurs. I apologise in advance if I have made a mistake in the coding, but I am relatively inexperienced. 

Best regards,
MRizakis

**Comment by MarkEdmondson1234** [comment]
Thanks for issue. Could you look at your example code and try to make a minimal reproducible example eg something we can run quickly and see the same issue without relying on lengthy downloads etc. 

This will both help diagnose any issues quickly and also may help you find any issues with your code itself.

**Comment by MRizakis** [comment]
Good evening,
Please accept my apologies for the late reply. I tried running a reprex, however I failed miserably. I possess no experience with creating reprexes for twitter data. I followed the steps and this is what it produced. I just filtered my dataset with this code in order to produce the dfm called minimum: minimu<-LePen_Patyb %>% filter(created_at>"2020-09-01",created_at<"2020-09-02")

``` r
library(rtweet)
library(tidyverse); theme_set(theme_minimal())
#> Warning: package 'tidyverse' was built under R version 4.0.5
#> Warning: package 'ggplot2' was built under R version 4.0.4
#> Warning: package 'tibble' was built under R version 4.0.5
#> Warning: package 'tidyr' was built under R version 4.0.5
#> Warning: package 'dplyr' was built under R version 4.0.5
#> Warning: package 'forcats' was built under R version 4.0.5
library(quanteda)
#> Warning: package 'quanteda' was built under R version 4.0.4
#> Package version: 2.1.2
#> Parallel computing: 2 of 8 threads used.
#> See https://quanteda.io for tutorials and examples.
#> 
#> Attaching package: 'quanteda'
#> The following object is masked from 'package:utils':
#> 
#>     View
library(stm)
#> stm v1.3.6 successfully loaded. See ?stm for help. 
#>  Papers, resources, and other materials at structuraltopicmodel.com
library(seededlda)
#> Warning: package 'seededlda' was built under R version 4.0.4
#> 
#> Attaching package: 'seededlda'
#> The following object is masked from 'package:stats':
#> 
#>     terms
library(stopwords)
#> Warning: package 'stopwords' was built under R version 4.0.4
library(stringi)
library(googleLanguageR)
#> Warning: package 'googleLanguageR' was built under R version 4.0.5

LePen_tr_2020<-gl_translate(minimum$text,target = "fr",format = c("text"),source = "")
#> Error in eval(assertion, env): object 'minimum' not found
```

<sup>Created on 2021-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The only other viable solution that I can think of is to provide you with an .rds of the data and my code. Please accept my apologies, but I am inexperienced and if no step-by-step guides are available, and tailored to my case I am lost.
Best regards,
MRizakis

**Comment by MarkEdmondson1234** [comment]
Thanks for the example - don't worry about the auth for me I got that. My guess is the object you are sending in is not text rather html. You may then get results if you specify the type as "html" and not the "text" default. If possible could you run str(object) on the exact thing that is being sent in, it will show its R class and structure.

**Comment by MRizakis** [comment]
Dear Mark,
The issue has been successfully  resolved and the package worked like a charm. Many thanks for taking the time to help me with the problem. 
Best regards,
M
![translatedJPG](https://user-images.githubusercontent.com/58853999/131252680-d2aa2f48-c93e-4a99-9d9e-8bc9e013d1c9.JPG)

**Comment by MarkEdmondson1234** [comment]
Great! Would you mind commenting your solution in case others have the same issue?

**Comment by MRizakis** [comment]
Dear Mark,
The mistake occurred due to a mix up. More specifically I had mixed up the target language with the source language. I know, it was rather stupid, and I apologise for taking up your time for such a simple oversight. Here is the code with the mistake. 
LePen_tr_2020<-gl_translate(minimum$text,target = "fr",format = c("text"),source = "")

**Comment by MarkEdmondson1234** [comment]
Ah no worries it happens to all of us!
