### ISSUE TITLE
Error midway and no translated text output

### ISSUE THREAD

**Issue by alovenegas** [ropensci/googleLanguageR#78]
I had to translate a vector of strings of 12955458 characters. I had performed similar requests in the same day and I had no problems in the past. Today the code stopped making requests midway and the console freezed and stopped displaying the message it generated every time a observation is being translated. I think it had to be an issue with the internet. The thing is it didn't continue making requests and I had no way to recover any output with the translation performed before the error. I had to restart R studio. I haven't recieved any invoice yet but the Google Cloud Console shows the requests traffic. Does this means I will get charged , even if there was no output at all? Or does the way this package conects to Google it only charges if an output is generated?

Thank you very much!

**Comment by MarkEdmondson1234** [comment]
Sorry for your trouble, it sounds like the http connection got interrupted and it will depend on when how much or if you would be charged. Perhaps for bigger files it's safest to use the cloud storage option since that decouples the file upload to the charged operation.

**Comment by alovenegas** [comment]
Hi Mark, thank you for your answer. Can you further explain this Cloud Storage option or where to specify it? Thank very much.

**Comment by MarkEdmondson1234** [comment]
Ah sorry :) I thought you were using speech to text function which involves uploading an audio file that can come from cloud storage. 

For translation your only option is uploading text. I can then only say to not translate big corpus at a time depending on your bandwidth. I've not heard of this issue before in several years so I guess you were unlucky this time :(
