### ISSUE TITLE
Example app using someones recorded audio via Shiny app

### ISSUE THREAD

**Issue by MarkEdmondson1234** [ropensci/googleLanguageR#8]
This module to record audio
https://github.com/nstrayer/shinysense/blob/master/demo/earr_demo.R

Audio to text, text to entity or text to translation.

**Comment by MarkEdmondson1234** [comment]
This is started on this branch https://github.com/ropensci/googleLanguageR/tree/shiny-demo

**Comment by amrrs** [comment]
Hi @MarkEdmondson1234 , Could you please elaborate on the ```enhancement``` you're looking for here?

**Comment by MarkEdmondson1234** [comment]
Hi @amrrs - I am looking to create a Shiny app that uses JavaScript to input an audio file that is recorded from the user's browser, then take that audio file and transcribe it in realtime using the Speech API.  Then I thought it would be cool to have some options that let you translate that text, or apply NLP to it.  I hope it can be used as a template that other users can build upon to make more useful applications.

The current state is that I've found a JS library that creates the audio file and looks to record it ok and sends to the API, but the JS is interfering with the DataTable used to display results(!) so either a better way to handle the recording or displaying the results in another manner would be cool.
